package mediarails

import "context"

// MediaType represents the kind of media operation.
type MediaType string

const (
	// TTS is text-to-speech generation.
	TTS MediaType = "tts"

	// STT is speech-to-text transcription.
	STT MediaType = "stt"

	// ImageGen is text-to-image generation.
	ImageGen MediaType = "image_gen"

	// VideoGen is text-to-video generation.
	VideoGen MediaType = "video_gen"

	// VideoFromImage is image-to-video generation.
	VideoFromImage MediaType = "video_from_img"
)

// Provider is the unified interface for all media generation providers.
// Implementations handle both synchronous and asynchronous generation.
type Provider interface {
	// ID returns the provider identifier (e.g., "elevenlabs", "fal").
	ID() string

	// SupportedTypes returns the media types this provider can handle.
	SupportedTypes() []MediaType

	// Generate initiates a media generation request. For synchronous providers,
	// the response contains the completed asset. For asynchronous providers,
	// the response contains a JobID for polling via CheckStatus.
	Generate(ctx context.Context, req *GenerateRequest) (*GenerateResponse, error)

	// CheckStatus polls the status of an async generation job.
	// Returns ErrNotAsync for synchronous-only providers.
	CheckStatus(ctx context.Context, jobID string) (*GenerateResponse, error)
}

// GenerateRequest contains the parameters for a media generation request.
type GenerateRequest struct {
	// Type is the media operation to perform.
	Type MediaType

	// Model is the provider-specific model identifier.
	Model string

	// Prompt is the text input for generation (TTS text, image prompt, etc.).
	Prompt string

	// InputURL is the URL of an input file (audio for STT, image for img-to-video).
	InputURL string

	// InputData is raw input bytes as an alternative to InputURL.
	InputData []byte

	// Config holds provider-specific parameters (voice_id, duration, etc.).
	Config map[string]any
}

// GenerateResponse contains the result of a media generation request.
type GenerateResponse struct {
	// JobID is the async job identifier. Empty for synchronous responses.
	JobID string

	// Status is the current job status.
	Status JobStatus

	// AssetURL is the URL of the generated asset (when completed).
	AssetURL string

	// AssetData is the raw generated bytes (for synchronous providers).
	AssetData []byte

	// ContentType is the MIME type of the generated asset.
	ContentType string

	// TextOutput contains transcribed text (for STT operations).
	TextOutput string

	// Usage contains metering information for cost calculation.
	Usage *Usage

	// Metadata holds provider-specific result information.
	Metadata map[string]any
}
